### ISSUE TITLE
ReferenceError during error handling

### ISSUE THREAD

**Issue by ZeeD** [andreadev-it/bg-script#1]
I just got bit by this error in the error handling :)

In https://github.com/andreadev-it/bg-script/blob/fd9906ea1a2866869765d8c04a65b507ff99c950/src/Connection.js#L216 there is a reference to the variable `result` that is not defined. 

I think the fix is trivial, should be enough to just replace `result` with `error`.

**Comment by andreadev-it** [comment]
Thank you a lot ZeeD!
This indeed is just a mistake, I've merged your pull request and updated the npm version of the library. Glad that someone is using it, thanks for your help 😄
